/* 1001 种精酿 — 数据集（分批建设中，目标 1001 款）
   每款均为真实、可核对的知名精酿：中文名 + 英文名 + 酒厂 + 风格家族(cat) + 具体风格 + 酒精度 + 产地
   风格家族 cat（精酿常规分类）:
     lager 拉格/皮尔森 | pale 淡色艾尔 | ipa 印度淡色艾尔(IPA) | wheat 小麦啤酒 |
     belgian 比利时艾尔 | stout 世涛与波特 | sour 酸啤与野啤 | amber 琥珀与棕色艾尔 |
     strong 烈性与桶陈 | specialty 特色与季节
   —— 种子批：约 150 款经典/传奇精酿，后续向 1001 扩充
*/
window.BEER_DATA = [

/* ============ 拉格 / 皮尔森 lager ============ */
{"id":1,"name":"皮尔森之源","name_en":"Pilsner Urquell","brewery":"皮尔森之源酒厂","brewery_en":"Plzeňský Prazdroj","cat":"lager","style":"捷克皮尔森","style_en":"Czech Pilsner","abv":"4.4%","origin":"捷克","origin_en":"Czech Republic","desc":"1842 年诞生于皮尔森，世界上第一款金黄色皮尔森啤酒。","desc_en":"Born in Plzeň in 1842, the world's first golden pilsner."},
{"id":2,"name":"捷克百威 Budvar","name_en":"Budweiser Budvar","brewery":"布杰约维采百威","brewery_en":"Budějovický Budvar","cat":"lager","style":"捷克淡拉格","style_en":"Czech Pale Lager","abv":"5.0%","origin":"捷克","origin_en":"Czech Republic","desc":"来自捷克百威市的原味拉格，与美国百威的百年商标之争主角。","desc_en":"The original Budweiser from Budweis, at the heart of a century-long trademark dispute."},
{"id":3,"name":"奥古斯丁淡拉格","name_en":"Augustiner Lagerbier Hell","brewery":"奥古斯丁酿造","brewery_en":"Augustiner-Bräu","cat":"lager","style":"慕尼黑淡色拉格","style_en":"Munich Helles","abv":"5.2%","origin":"德国","origin_en":"Germany","desc":"慕尼黑最受当地人爱戴的海拉斯，绿瓶经典。","desc_en":"Munich's most beloved Helles, an icon in its green bottle."},
{"id":4,"name":"维森海拉斯","name_en":"Weihenstephaner Original Helles","brewery":"维森斯特凡","brewery_en":"Weihenstephan","cat":"lager","style":"淡色拉格","style_en":"Munich Helles","abv":"5.1%","origin":"德国","origin_en":"Germany","desc":"号称世界最古老酒厂(1040)出品的清爽海拉斯。","desc_en":"A crisp Helles from what claims to be the world's oldest brewery (1040)."},
{"id":5,"name":"黑森林松塔","name_en":"Rothaus Tannenzäpfle Pils","brewery":"罗陶斯","brewery_en":"Rothaus","cat":"lager","style":"德式皮尔森","style_en":"German Pils","abv":"5.1%","origin":"德国","origin_en":"Germany","desc":"黑森林高地国营酒厂的小松塔，德国人气皮尔森。","desc_en":"The 'little fir cone' Pils from a Black Forest state brewery."},
{"id":6,"name":"耶佛皮尔森","name_en":"Jever Pilsener","brewery":"耶佛","brewery_en":"Friesisches Brauhaus zu Jever","cat":"lager","style":"德式皮尔森","style_en":"German Pils","abv":"4.9%","origin":"德国","origin_en":"Germany","desc":"北德弗里斯兰风格，以极干爽苦度著称。","desc_en":"North German Frisian style, famed for its bracing dry bitterness."},
{"id":7,"name":"碧特博格","name_en":"Bitburger Premium Pils","brewery":"碧特博格","brewery_en":"Bitburger","cat":"lager","style":"德式皮尔森","style_en":"German Pils","abv":"4.8%","origin":"德国","origin_en":"Germany","desc":"德国销量最大的桶啤之一，干净利落。","desc_en":"One of Germany's best-selling draught Pils, clean and crisp."},
{"id":8,"name":"卡力特黑啤","name_en":"Köstritzer Schwarzbier","brewery":"卡力特","brewery_en":"Köstritzer","cat":"lager","style":"黑拉格","style_en":"Schwarzbier","abv":"4.8%","origin":"德国","origin_en":"Germany","desc":"歌德钟爱的黑色拉格，焦香却清爽。","desc_en":"A black lager beloved by Goethe—roasty yet clean."},
{"id":9,"name":"艾英格庆祝者","name_en":"Ayinger Celebrator","brewery":"艾英格","brewery_en":"Ayinger","cat":"lager","style":"双料博克","style_en":"Doppelbock","abv":"6.7%","origin":"德国","origin_en":"Germany","desc":"瓶身挂小山羊的经典双料博克，麦香醇厚。","desc_en":"The classic Doppelbock with a little goat charm on the bottle."},
{"id":10,"name":"保拉纳圣者","name_en":"Paulaner Salvator","brewery":"保拉纳","brewery_en":"Paulaner","cat":"lager","style":"双料博克","style_en":"Doppelbock","abv":"7.9%","origin":"德国","origin_en":"Germany","desc":"修士封斋期的'液体面包'，双料博克鼻祖。","desc_en":"The monks' 'liquid bread' for Lent—the original Doppelbock."},
{"id":11,"name":"圣诞老人","name_en":"Samichlaus Classic","brewery":"艾根堡城堡酒厂","brewery_en":"Schloss Eggenberg","cat":"lager","style":"双料博克","style_en":"Doppelbock","abv":"14%","origin":"奥地利","origin_en":"Austria","desc":"每年仅在圣尼古拉日酿造一次，曾是世界最烈的拉格。","desc_en":"Brewed once a year on St. Nicholas Day; once the world's strongest lager."},
{"id":12,"name":"山姆亚当斯波士顿拉格","name_en":"Samuel Adams Boston Lager","brewery":"波士顿啤酒公司","brewery_en":"Boston Beer Co.","cat":"lager","style":"维也纳拉格","style_en":"Vienna Lager","abv":"5.0%","origin":"美国","origin_en":"USA","desc":"点燃美国精酿革命的旗舰维也纳拉格(1984)。","desc_en":"The flagship Vienna Lager that helped ignite America's craft revolution."},
{"id":13,"name":"胜利精酿皮尔森","name_en":"Victory Prima Pils","brewery":"胜利酿造","brewery_en":"Victory Brewing","cat":"lager","style":"德式皮尔森","style_en":"German Pils","abv":"5.3%","origin":"美国","origin_en":"USA","desc":"美国精酿皮尔森标杆，德国啤酒花大方投放。","desc_en":"A benchmark American craft Pils, generously German-hopped."},
{"id":14,"name":"石墙 Pivo 皮尔森","name_en":"Firestone Walker Pivo Pils","brewery":"石墙","brewery_en":"Firestone Walker","cat":"lager","style":"意式干投皮尔森","style_en":"Italian-style Pils","abv":"5.3%","origin":"美国","origin_en":"USA","desc":"干投啤酒花的意式皮尔森，花香与脆爽兼备。","desc_en":"A dry-hopped Italian-style Pils balancing aroma and crisp bite."},
{"id":15,"name":"艾英格十月节","name_en":"Ayinger Oktoberfest-Märzen","brewery":"艾英格","brewery_en":"Ayinger","cat":"lager","style":"三月/十月节拉格","style_en":"Märzen","abv":"5.8%","origin":"德国","origin_en":"Germany","desc":"金铜色的十月节拉格，麦芽面包香饱满。","desc_en":"A copper-gold Oktoberfest lager, full of bready malt."},
{"id":16,"name":"维森柯比年","name_en":"Weihenstephaner Korbinian","brewery":"维森斯特凡","brewery_en":"Weihenstephan","cat":"lager","style":"双料博克","style_en":"Doppelbock","abv":"7.4%","origin":"德国","origin_en":"Germany","desc":"深栗色双料博克，焦糖与干果风味。","desc_en":"A deep chestnut Doppelbock with caramel and dried fruit."},
{"id":17,"name":"五大湖多特蒙德金","name_en":"Great Lakes Dortmunder Gold","brewery":"五大湖","brewery_en":"Great Lakes","cat":"lager","style":"多特蒙德出口型","style_en":"Dortmunder Export","abv":"5.8%","origin":"美国","origin_en":"USA","desc":"屡获金奖的多特蒙德出口型拉格。","desc_en":"An award-laden Dortmunder Export lager."},
{"id":18,"name":"诺奇小憩皮尔森","name_en":"Notch Session Pils","brewery":"诺奇","brewery_en":"Notch","cat":"lager","style":"捷克皮尔森","style_en":"Czech Pilsner","abv":"4.0%","origin":"美国","origin_en":"USA","desc":"专注低度的酒厂，低酒精捷克式皮尔森。","desc_en":"From a session-only brewery—a low-ABV Czech-style Pils."},

/* ============ 淡色艾尔 pale ============ */
{"id":19,"name":"内华达山脉淡色艾尔","name_en":"Sierra Nevada Pale Ale","brewery":"内华达山脉","brewery_en":"Sierra Nevada","cat":"pale","style":"美式淡色艾尔","style_en":"American Pale Ale","abv":"5.6%","origin":"美国","origin_en":"USA","desc":"1980 年问世，美式精酿的开山之作与卡斯卡特花香范本。","desc_en":"The 1980 beer that defined American craft and the Cascade-hop aroma."},
{"id":20,"name":"僵尸尘埃","name_en":"Zombie Dust","brewery":"三个弗洛伊德","brewery_en":"Three Floyds","cat":"pale","style":"美式淡色艾尔","style_en":"American Pale Ale","abv":"6.4%","origin":"美国","origin_en":"USA","desc":"单一西楚花酿造的膜拜级淡色艾尔。","desc_en":"A single-hop Citra pale ale with a cult following."},
{"id":21,"name":"镜潭淡色艾尔","name_en":"Deschutes Mirror Pond","brewery":"迪舒特","brewery_en":"Deschutes","cat":"pale","style":"美式淡色艾尔","style_en":"American Pale Ale","abv":"5.0%","origin":"美国","origin_en":"USA","desc":"俄勒冈经典，单一卡斯卡特花的均衡淡色艾尔。","desc_en":"An Oregon classic, a balanced all-Cascade pale ale."},
{"id":22,"name":"雏菊割草机","name_en":"Half Acre Daisy Cutter","brewery":"半英亩","brewery_en":"Half Acre","cat":"pale","style":"美式淡色艾尔","style_en":"American Pale Ale","abv":"5.2%","origin":"美国","origin_en":"USA","desc":"芝加哥人气罐装淡色艾尔，柑橘松脂扑鼻。","desc_en":"Chicago's cult canned pale ale, bursting with citrus and pine."},
{"id":23,"name":"石墙 31 号淡色","name_en":"Firestone Walker Pale 31","brewery":"石墙","brewery_en":"Firestone Walker","cat":"pale","style":"美式淡色艾尔","style_en":"American Pale Ale","abv":"4.9%","origin":"美国","origin_en":"USA","desc":"加州风格淡色艾尔，柑橘清爽易饮。","desc_en":"A California-style pale ale—citrusy and eminently drinkable."},
{"id":24,"name":"铁锚自由艾尔","name_en":"Anchor Liberty Ale","brewery":"铁锚","brewery_en":"Anchor Brewing","cat":"pale","style":"美式淡色艾尔","style_en":"American Pale Ale","abv":"5.9%","origin":"美国","origin_en":"USA","desc":"1975 年首创干投卡斯卡特，现代美式艾尔的先声。","desc_en":"The 1975 pioneer of dry-hopped Cascade—a forerunner of American ale."},
{"id":25,"name":"假苏","name_en":"Toppling Goliath Pseudo Sue","brewery":"推倒歌利亚","brewery_en":"Toppling Goliath","cat":"pale","style":"美式淡色艾尔","style_en":"American Pale Ale","abv":"5.8%","origin":"美国","origin_en":"USA","desc":"以霸王龙化石命名，单一西楚花的高分淡色艾尔。","desc_en":"Named for a T. rex fossil—a highly rated single-Citra pale ale."},
{"id":26,"name":"富勒伦敦骄傲","name_en":"Fuller's London Pride","brewery":"富勒","brewery_en":"Fuller's","cat":"pale","style":"英式苦啤","style_en":"English Bitter","abv":"4.7%","origin":"英国","origin_en":"UK","desc":"伦敦最著名的传统苦啤，麦香均衡。","desc_en":"London's most famous traditional bitter, malty and balanced."},
{"id":27,"name":"房东","name_en":"Timothy Taylor Landlord","brewery":"提摩西泰勒","brewery_en":"Timothy Taylor","cat":"pale","style":"英式淡色艾尔","style_en":"English Pale Ale","abv":"4.3%","origin":"英国","origin_en":"UK","desc":"约克郡屡获殊荣的经典桶内熟成淡色艾尔。","desc_en":"A multi-award-winning Yorkshire cask pale ale."},
{"id":28,"name":"伽马射线","name_en":"Gamma Ray","brewery":"海狸镇","brewery_en":"Beavertown","cat":"pale","style":"美式淡色艾尔","style_en":"American Pale Ale","abv":"5.4%","origin":"英国","origin_en":"UK","desc":"伦敦新浪潮酒厂的招牌，热带果香浓郁。","desc_en":"The flagship of a London new-wave brewery, packed with tropical fruit."},

/* ============ 印度淡色艾尔 IPA ============ */
{"id":29,"name":"老普林尼","name_en":"Pliny the Elder","brewery":"俄罗斯河","brewery_en":"Russian River","cat":"ipa","style":"双料IPA","style_en":"Double IPA","abv":"8.0%","origin":"美国","origin_en":"USA","desc":"西海岸双料IPA的黄金标准，一代传奇。","desc_en":"The gold standard of the West Coast Double IPA—an all-time legend."},
{"id":30,"name":"小普林尼","name_en":"Pliny the Younger","brewery":"俄罗斯河","brewery_en":"Russian River","cat":"ipa","style":"三料IPA","style_en":"Triple IPA","abv":"10.25%","origin":"美国","origin_en":"USA","desc":"每年二月限量放出，引发通宵排队的三料IPA。","desc_en":"A February-only triple IPA that draws overnight queues."},
{"id":31,"name":"云端","name_en":"Heady Topper","brewery":"炼金术士","brewery_en":"The Alchemist","cat":"ipa","style":"新英格兰双料IPA","style_en":"New England Double IPA","abv":"8.0%","origin":"美国","origin_en":"USA","desc":"佛蒙特浑浊IPA鼻祖，'别倒进杯子'的膜拜罐。","desc_en":"The Vermont haze pioneer—the cult can that says 'drink from the can'."},
{"id":32,"name":"焦点炮手","name_en":"Focal Banger","brewery":"炼金术士","brewery_en":"The Alchemist","cat":"ipa","style":"美式IPA","style_en":"American IPA","abv":"7.0%","origin":"美国","origin_en":"USA","desc":"云端的姊妹作，西楚与摩西干投果香四溢。","desc_en":"Heady Topper's sibling, bursting with Citra and Mosaic."},
{"id":33,"name":"两颗心","name_en":"Two Hearted Ale","brewery":"贝尔","brewery_en":"Bell's","cat":"ipa","style":"美式IPA","style_en":"American IPA","abv":"7.0%","origin":"美国","origin_en":"USA","desc":"单一世纪花IPA，多年蝉联爱好者票选第一。","desc_en":"An all-Centennial IPA, repeatedly voted #1 by enthusiasts."},
{"id":34,"name":"鲉鱼","name_en":"Sculpin IPA","brewery":"压舱石","brewery_en":"Ballast Point","cat":"ipa","style":"美式IPA","style_en":"American IPA","abv":"7.0%","origin":"美国","origin_en":"USA","desc":"圣地亚哥经典，桃杏柑橘般的明快IPA。","desc_en":"A San Diego classic, bright with peach, apricot and citrus."},
{"id":35,"name":"60分钟IPA","name_en":"60 Minute IPA","brewery":"角鲨头","brewery_en":"Dogfish Head","cat":"ipa","style":"美式IPA","style_en":"American IPA","abv":"6.0%","origin":"美国","origin_en":"USA","desc":"煮沸全程连续投花 60 分钟的日常口粮IPA。","desc_en":"Continuously hopped for a full 60-minute boil—the everyday IPA."},
{"id":36,"name":"90分钟IPA","name_en":"90 Minute IPA","brewery":"角鲨头","brewery_en":"Dogfish Head","cat":"ipa","style":"帝国IPA","style_en":"Imperial IPA","abv":"9.0%","origin":"美国","origin_en":"USA","desc":"连续投花 90 分钟，麦香与酒花势均力敌。","desc_en":"90 minutes of continuous hopping—malt and hops in balance."},
{"id":37,"name":"回力球IPA","name_en":"Jai Alai IPA","brewery":"雪茄城","brewery_en":"Cigar City","cat":"ipa","style":"美式IPA","style_en":"American IPA","abv":"7.5%","origin":"美国","origin_en":"USA","desc":"坦帕招牌，柑橘与热带水果的浓郁IPA。","desc_en":"Tampa's signature—a robust IPA of citrus and tropical fruit."},
{"id":38,"name":"朱利叶斯","name_en":"Julius","brewery":"树屋","brewery_en":"Tree House","cat":"ipa","style":"新英格兰IPA","style_en":"New England IPA","abv":"6.8%","origin":"美国","origin_en":"USA","desc":"树屋的招牌浑浊IPA，柔滑多汁。","desc_en":"Tree House's flagship hazy IPA—soft and juicy."},
{"id":39,"name":"阳光一口","name_en":"Sip of Sunshine","brewery":"劳森上品","brewery_en":"Lawson's Finest","cat":"ipa","style":"帝国IPA","style_en":"Imperial IPA","abv":"8.0%","origin":"美国","origin_en":"USA","desc":"佛蒙特帝国IPA，明亮柑橘与热带风情。","desc_en":"A Vermont imperial IPA, bright with citrus and tropics."},
{"id":40,"name":"米字旗IPA","name_en":"Union Jack IPA","brewery":"石墙","brewery_en":"Firestone Walker","cat":"ipa","style":"西海岸IPA","style_en":"West Coast IPA","abv":"7.0%","origin":"美国","origin_en":"USA","desc":"干投六种啤酒花的锋利西海岸IPA。","desc_en":"A sharp West Coast IPA dry-hopped with six varieties."},
{"id":41,"name":"5号赛车手","name_en":"Racer 5 IPA","brewery":"熊共和国","brewery_en":"Bear Republic","cat":"ipa","style":"美式IPA","style_en":"American IPA","abv":"7.0%","origin":"美国","origin_en":"USA","desc":"北加州获奖无数的经典美式IPA。","desc_en":"A NorCal classic American IPA laden with medals."},
{"id":42,"name":"绿闪西海岸IPA","name_en":"Green Flash West Coast IPA","brewery":"绿闪","brewery_en":"Green Flash","cat":"ipa","style":"西海岸IPA","style_en":"West Coast IPA","abv":"8.1%","origin":"美国","origin_en":"USA","desc":"以'西海岸IPA'命名，苦味锋锐的教科书之作。","desc_en":"The textbook that put 'West Coast IPA' on the label."},
{"id":43,"name":"石头IPA","name_en":"Stone IPA","brewery":"巨石","brewery_en":"Stone Brewing","cat":"ipa","style":"美式IPA","style_en":"American IPA","abv":"6.9%","origin":"美国","origin_en":"USA","desc":"石头酒厂的旗舰，坚定的酒花主义宣言。","desc_en":"Stone's flagship—an unapologetic hop manifesto."},
{"id":44,"name":"拉古尼塔斯IPA","name_en":"Lagunitas IPA","brewery":"拉古尼塔斯","brewery_en":"Lagunitas","cat":"ipa","style":"美式IPA","style_en":"American IPA","abv":"6.2%","origin":"美国","origin_en":"USA","desc":"加州销量巨头，均衡好喝的入门美式IPA。","desc_en":"A California juggernaut—balanced and approachable."},
{"id":45,"name":"朦胧小东西","name_en":"Hazy Little Thing","brewery":"内华达山脉","brewery_en":"Sierra Nevada","cat":"ipa","style":"浑浊IPA","style_en":"Hazy IPA","abv":"6.7%","origin":"美国","origin_en":"USA","desc":"把浑浊IPA带入主流的未过滤罐装作品。","desc_en":"The unfiltered can that took hazy IPA mainstream."},
{"id":46,"name":"全天IPA","name_en":"All Day IPA","brewery":"创始人","brewery_en":"Founders","cat":"ipa","style":"小憩IPA","style_en":"Session IPA","abv":"4.7%","origin":"美国","origin_en":"USA","desc":"低度高香的口粮IPA，开创小憩IPA潮流。","desc_en":"A low-ABV, high-flavor sessionable IPA that started a trend."},
{"id":47,"name":"朋克IPA","name_en":"Punk IPA","brewery":"酿酒狗","brewery_en":"BrewDog","cat":"ipa","style":"美式IPA","style_en":"American IPA","abv":"5.4%","origin":"英国","origin_en":"UK","desc":"点燃英国精酿革命的旗舰IPA。","desc_en":"The flagship IPA that sparked Britain's craft revolution."},
{"id":48,"name":"猫王果汁","name_en":"Elvis Juice","brewery":"酿酒狗","brewery_en":"BrewDog","cat":"ipa","style":"西柚IPA","style_en":"Grapefruit IPA","abv":"6.5%","origin":"英国","origin_en":"UK","desc":"加入西柚皮的IPA，苦甜交织。","desc_en":"An IPA infused with grapefruit peel, bittersweet and zesty."},
{"id":49,"name":"颈油小憩IPA","name_en":"Neck Oil","brewery":"海狸镇","brewery_en":"Beavertown","cat":"ipa","style":"小憩IPA","style_en":"Session IPA","abv":"4.3%","origin":"英国","origin_en":"UK","desc":"伦敦口粮小憩IPA，轻盈果香。","desc_en":"A London session IPA—light and fruity."},
{"id":50,"name":"云水双料IPA","name_en":"Cloudwater DIPA","brewery":"云水","brewery_en":"Cloudwater","cat":"ipa","style":"双料IPA","style_en":"Double IPA","abv":"8.0%","origin":"英国","origin_en":"UK","desc":"曼彻斯特浑浊双料IPA，引领英国新浪潮。","desc_en":"A Manchester hazy DIPA leading Britain's new wave."},
{"id":51,"name":"鲜榨IPA","name_en":"Fresh Squeezed IPA","brewery":"迪舒特","brewery_en":"Deschutes","cat":"ipa","style":"美式IPA","style_en":"American IPA","abv":"6.4%","origin":"美国","origin_en":"USA","desc":"西楚与摩西花带来鲜榨橙汁般果香。","desc_en":"Citra and Mosaic give it a fresh-squeezed-juice character."},
{"id":52,"name":"啤酒花猛击","name_en":"Hopslam Ale","brewery":"贝尔","brewery_en":"Bell's","cat":"ipa","style":"双料IPA","style_en":"Double IPA","abv":"10.0%","origin":"美国","origin_en":"USA","desc":"每年限量、加蜂蜜的重磅双料IPA。","desc_en":"A limited, honey-kissed double IPA released once a year."},
{"id":53,"name":"盲猪IPA","name_en":"Blind Pig IPA","brewery":"俄罗斯河","brewery_en":"Russian River","cat":"ipa","style":"美式IPA","style_en":"American IPA","abv":"6.1%","origin":"美国","origin_en":"USA","desc":"老普林尼的'小弟'，同样锋利多汁。","desc_en":"Pliny's little sibling—sharp and juicy."},
{"id":54,"name":"缅因午餐IPA","name_en":"Lunch","brewery":"缅因啤酒公司","brewery_en":"Maine Beer Co.","cat":"ipa","style":"美式IPA","style_en":"American IPA","abv":"7.0%","origin":"美国","origin_en":"USA","desc":"以一头友好鲸鱼为名的高分IPA。","desc_en":"A highly rated IPA named after a friendly whale."},

/* ============ 小麦啤酒 wheat ============ */
{"id":55,"name":"维森小麦","name_en":"Weihenstephaner Hefeweissbier","brewery":"维森斯特凡","brewery_en":"Weihenstephan","cat":"wheat","style":"德式酵母小麦","style_en":"Hefeweizen","abv":"5.4%","origin":"德国","origin_en":"Germany","desc":"公认的德式小麦标杆，香蕉与丁香交织。","desc_en":"The benchmark Hefeweizen—banana and clove in harmony."},
{"id":56,"name":"施耐德 Tap 7","name_en":"Schneider Weisse Original","brewery":"施耐德","brewery_en":"Schneider","cat":"wheat","style":"琥珀小麦","style_en":"Hefeweizen","abv":"5.4%","origin":"德国","origin_en":"Germany","desc":"深色琥珀小麦，麦香与焦糖更浓。","desc_en":"An amber wheat beer with deeper malt and caramel notes."},
{"id":57,"name":"艾丁格小麦","name_en":"Erdinger Weissbier","brewery":"艾丁格","brewery_en":"Erdinger","cat":"wheat","style":"德式酵母小麦","style_en":"Hefeweizen","abv":"5.3%","origin":"德国","origin_en":"Germany","desc":"世界最大专业小麦啤酒厂的招牌。","desc_en":"The flagship of the world's largest wheat-beer brewery."},
{"id":58,"name":"范佳乐(教士)","name_en":"Franziskaner Hefe-Weissbier","brewery":"斯巴顿-范佳乐","brewery_en":"Spaten-Franziskaner","cat":"wheat","style":"德式酵母小麦","style_en":"Hefeweizen","abv":"5.0%","origin":"德国","origin_en":"Germany","desc":"瓶身修士像的慕尼黑经典小麦。","desc_en":"The Munich classic with a friar on the label."},
{"id":59,"name":"保拉纳小麦","name_en":"Paulaner Hefe-Weißbier","brewery":"保拉纳","brewery_en":"Paulaner","cat":"wheat","style":"德式酵母小麦","style_en":"Hefeweizen","abv":"5.5%","origin":"德国","origin_en":"Germany","desc":"慕尼黑六大之一的自然浑浊小麦。","desc_en":"Naturally cloudy wheat from one of Munich's big six."},
{"id":60,"name":"施耐德阿文丁","name_en":"Schneider Aventinus","brewery":"施耐德","brewery_en":"Schneider","cat":"wheat","style":"小麦博克","style_en":"Weizenbock","abv":"8.2%","origin":"德国","origin_en":"Germany","desc":"深色烈性小麦博克，李子与丁香交织。","desc_en":"A dark, strong wheat bock of plum and clove."},
{"id":61,"name":"福佳白","name_en":"Hoegaarden","brewery":"福佳","brewery_en":"Hoegaarden","cat":"wheat","style":"比利时白啤","style_en":"Witbier","abv":"4.9%","origin":"比利时","origin_en":"Belgium","desc":"复兴比利时白啤的经典，橙皮与芫荽调味。","desc_en":"The classic that revived Belgian witbier—orange peel and coriander."},
{"id":62,"name":"阿拉加什白","name_en":"Allagash White","brewery":"阿拉加什","brewery_en":"Allagash","cat":"wheat","style":"比利时白啤","style_en":"Witbier","abv":"5.2%","origin":"美国","origin_en":"USA","desc":"美式比利时白啤标杆，香料清新。","desc_en":"The benchmark American witbier—spiced and refreshing."},
{"id":63,"name":"蓝月","name_en":"Blue Moon Belgian White","brewery":"蓝月","brewery_en":"Blue Moon","cat":"wheat","style":"比利时白啤","style_en":"Witbier","abv":"5.4%","origin":"美国","origin_en":"USA","desc":"配橙片饮用而走红的美式白啤。","desc_en":"The American wit made famous served with an orange slice."},
{"id":64,"name":"圣伯纳白啤","name_en":"St. Bernardus Wit","brewery":"圣伯纳","brewery_en":"St. Bernardus","cat":"wheat","style":"比利时白啤","style_en":"Witbier","abv":"5.5%","origin":"比利时","origin_en":"Belgium","desc":"由白啤之父配方打造的顶级比利时白啤。","desc_en":"A top-tier witbier crafted from the recipe of the style's father."},
{"id":65,"name":"奥伯龙","name_en":"Bell's Oberon","brewery":"贝尔","brewery_en":"Bell's","cat":"wheat","style":"美式小麦","style_en":"American Wheat","abv":"5.8%","origin":"美国","origin_en":"USA","desc":"密歇根的夏日信使，每年春天限时回归。","desc_en":"Michigan's herald of summer, returning each spring."},
{"id":66,"name":"泡泡糖","name_en":"Gumballhead","brewery":"三个弗洛伊德","brewery_en":"Three Floyds","cat":"wheat","style":"美式小麦","style_en":"American Wheat","abv":"5.6%","origin":"美国","origin_en":"USA","desc":"大量投花的美式小麦，柑橘花香突出。","desc_en":"A heavily hopped American wheat, big on citrus aroma."},
{"id":67,"name":"柏林小麦","name_en":"Berliner Kindl Weisse","brewery":"柏林之子","brewery_en":"Berliner Kindl","cat":"wheat","style":"柏林酸小麦","style_en":"Berliner Weisse","abv":"3.0%","origin":"德国","origin_en":"Germany","desc":"低度微酸的柏林小麦，常配糖浆饮用。","desc_en":"A low, tart Berlin wheat, often served with syrup."},

/* ============ 比利时艾尔 belgian ============ */
{"id":68,"name":"西弗莱特伦12号","name_en":"Westvleteren 12","brewery":"西弗莱特伦圣西斯笃修道院","brewery_en":"Westvleteren (St. Sixtus)","cat":"belgian","style":"四料","style_en":"Quadrupel","abv":"10.2%","origin":"比利时","origin_en":"Belgium","desc":"只在修道院门口限量出售，屡被评为世界第一。","desc_en":"Sold only at the abbey gate—repeatedly rated the world's best beer."},
{"id":69,"name":"西麦尔三料","name_en":"Westmalle Tripel","brewery":"西麦尔","brewery_en":"Westmalle","cat":"belgian","style":"三料","style_en":"Tripel","abv":"9.5%","origin":"比利时","origin_en":"Belgium","desc":"定义'三料'风格的修道院经典。","desc_en":"The Trappist classic that defined the Tripel style."},
{"id":70,"name":"西麦尔双料","name_en":"Westmalle Dubbel","brewery":"西麦尔","brewery_en":"Westmalle","cat":"belgian","style":"双料","style_en":"Dubbel","abv":"7.0%","origin":"比利时","origin_en":"Belgium","desc":"深栗色双料范本，干果与焦糖气息。","desc_en":"The archetypal Dubbel—dark fruit and caramel."},
{"id":71,"name":"智美蓝帽","name_en":"Chimay Bleue","brewery":"智美","brewery_en":"Chimay","cat":"belgian","style":"比利时烈性深色艾尔","style_en":"Belgian Strong Dark","abv":"9.0%","origin":"比利时","origin_en":"Belgium","desc":"智美旗舰，随陈年愈发醇厚的修道院烈艾。","desc_en":"Chimay's flagship, a Trappist strong ale that ages gracefully."},
{"id":72,"name":"智美红帽","name_en":"Chimay Rouge","brewery":"智美","brewery_en":"Chimay","cat":"belgian","style":"双料","style_en":"Dubbel","abv":"7.0%","origin":"比利时","origin_en":"Belgium","desc":"智美最早的产品，铜色双料。","desc_en":"Chimay's original—a copper-hued Dubbel."},
{"id":73,"name":"智美白帽","name_en":"Chimay Cinq Cents","brewery":"智美","brewery_en":"Chimay","cat":"belgian","style":"三料","style_en":"Tripel","abv":"8.0%","origin":"比利时","origin_en":"Belgium","desc":"金色三料，酒花与柑橘气息更明快。","desc_en":"A golden Tripel with brighter hop and citrus notes."},
{"id":74,"name":"罗斯福10号","name_en":"Rochefort 10","brewery":"罗斯福","brewery_en":"Rochefort","cat":"belgian","style":"四料","style_en":"Quadrupel","abv":"11.3%","origin":"比利时","origin_en":"Belgium","desc":"深沉复杂的修道院四料，无花果与波特酒气息。","desc_en":"A deep, complex Trappist quad of figs and port."},
{"id":75,"name":"罗斯福8号","name_en":"Rochefort 8","brewery":"罗斯福","brewery_en":"Rochefort","cat":"belgian","style":"比利时烈性深色艾尔","style_en":"Belgian Strong Dark","abv":"9.2%","origin":"比利时","origin_en":"Belgium","desc":"许多人心中最均衡的罗斯福。","desc_en":"For many, the most balanced Rochefort."},
{"id":76,"name":"奥威","name_en":"Orval","brewery":"奥威","brewery_en":"Orval","cat":"belgian","style":"修道院艾尔","style_en":"Belgian Pale/Trappist","abv":"6.2%","origin":"比利时","origin_en":"Belgium","desc":"加入酒香酵母干投，随陈放不断变化的独一无二之作。","desc_en":"Brettanomyces-dry-hopped and ever-evolving—utterly unique."},
{"id":77,"name":"圣伯纳12号","name_en":"St. Bernardus Abt 12","brewery":"圣伯纳","brewery_en":"St. Bernardus","cat":"belgian","style":"四料","style_en":"Quadrupel","abv":"10.0%","origin":"比利时","origin_en":"Belgium","desc":"与西弗莱特伦同源配方的顶级四料。","desc_en":"A top-tier quad sharing lineage with Westvleteren."},
{"id":78,"name":"督威","name_en":"Duvel","brewery":"督威摩盖特","brewery_en":"Duvel Moortgat","cat":"belgian","style":"比利时烈性金色艾尔","style_en":"Belgian Strong Golden","abv":"8.5%","origin":"比利时","origin_en":"Belgium","desc":"金色气泡丰盈、暗藏'魔鬼'烈度的经典。","desc_en":"Golden and effervescent, hiding a devilish strength."},
{"id":79,"name":"粉象","name_en":"Delirium Tremens","brewery":"于格","brewery_en":"Huyghe","cat":"belgian","style":"比利时烈性金色艾尔","style_en":"Belgian Strong Golden","abv":"8.5%","origin":"比利时","origin_en":"Belgium","desc":"粉红大象瓶身，全球知名的比利时金色烈艾。","desc_en":"The pink-elephant bottle—a world-famous Belgian strong ale."},
{"id":80,"name":"圣佳三料","name_en":"Tripel Karmeliet","brewery":"博斯特尔斯","brewery_en":"Bosteels","cat":"belgian","style":"三料","style_en":"Tripel","abv":"8.4%","origin":"比利时","origin_en":"Belgium","desc":"三种谷物酿造，香蕉与香草般顺滑。","desc_en":"Brewed with three grains—silky with banana and vanilla."},
{"id":81,"name":"舒弗精灵","name_en":"La Chouffe","brewery":"阿舒弗","brewery_en":"Achouffe","cat":"belgian","style":"比利时烈性金色艾尔","style_en":"Belgian Strong Golden","abv":"8.0%","origin":"比利时","origin_en":"Belgium","desc":"红帽小精灵标志，果香辛香并存。","desc_en":"The red-hooded gnome ale—fruity and spicy."},
{"id":82,"name":"杜邦季节","name_en":"Saison Dupont","brewery":"杜邦","brewery_en":"Dupont","cat":"belgian","style":"季节啤酒","style_en":"Saison","abv":"6.5%","origin":"比利时","origin_en":"Belgium","desc":"定义'季节'风格的农舍艾尔，干爽辛香。","desc_en":"The farmhouse ale that defines the Saison—dry and peppery."},
{"id":83,"name":"金龙","name_en":"Gulden Draak","brewery":"范斯滕贝格","brewery_en":"Van Steenberge","cat":"belgian","style":"比利时烈性深色艾尔","style_en":"Belgian Strong Dark","abv":"10.5%","origin":"比利时","origin_en":"Belgium","desc":"三料深色烈艾，以根特金龙命名。","desc_en":"A dark tripel-strength ale named for Ghent's golden dragon."},
{"id":84,"name":"快克","name_en":"Pauwel Kwak","brewery":"博斯特尔斯","brewery_en":"Bosteels","cat":"belgian","style":"比利时琥珀烈艾","style_en":"Belgian Amber Strong","abv":"8.4%","origin":"比利时","origin_en":"Belgium","desc":"以独特木架马车杯著称的琥珀烈艾。","desc_en":"An amber strong ale famed for its coachman's stirrup glass."},
{"id":85,"name":"世界末日","name_en":"La Fin du Monde","brewery":"尤妮布罗","brewery_en":"Unibroue","cat":"belgian","style":"三料","style_en":"Belgian Tripel","abv":"9.0%","origin":"加拿大","origin_en":"Canada","desc":"魁北克致敬比利时三料的招牌之作。","desc_en":"Quebec's flagship homage to the Belgian Tripel."},
{"id":86,"name":"奥美加汉纳平季节","name_en":"Hennepin","brewery":"奥美加","brewery_en":"Ommegang","cat":"belgian","style":"季节啤酒","style_en":"Saison","abv":"7.7%","origin":"美国","origin_en":"USA","desc":"纽约比利时风酒厂的经典季节艾尔。","desc_en":"A classic Saison from a New York Belgian-style brewery."},
{"id":87,"name":"乐飞金","name_en":"Leffe Blonde","brewery":"乐飞","brewery_en":"Leffe","cat":"belgian","style":"比利时金色艾尔","style_en":"Belgian Blonde","abv":"6.6%","origin":"比利时","origin_en":"Belgium","desc":"修道院风格金色艾尔，全球最易得的比利时艾尔之一。","desc_en":"An abbey-style blonde, among the most widely available Belgian ales."},
{"id":88,"name":"拉初四料","name_en":"La Trappe Quadrupel","brewery":"拉初(科宁斯霍芬)","brewery_en":"La Trappe","cat":"belgian","style":"四料","style_en":"Quadrupel","abv":"10.0%","origin":"荷兰","origin_en":"Netherlands","desc":"荷兰唯一的修道院酒厂，'四料'一词由此确立。","desc_en":"The Netherlands' only Trappist brewery, which coined 'Quadrupel'."},

/* ============ 世涛与波特 stout ============ */
{"id":89,"name":"健力士生啤","name_en":"Guinness Draught","brewery":"健力士","brewery_en":"Guinness","cat":"stout","style":"爱尔兰干世涛","style_en":"Irish Dry Stout","abv":"4.2%","origin":"爱尔兰","origin_en":"Ireland","desc":"氮气推动的绵密奶盖，世界上最著名的世涛。","desc_en":"Nitrogen-poured with a creamy head—the world's most famous stout."},
{"id":90,"name":"早餐世涛","name_en":"Breakfast Stout","brewery":"创始人","brewery_en":"Founders","cat":"stout","style":"燕麦咖啡世涛","style_en":"Oatmeal Coffee Stout","abv":"8.3%","origin":"美国","origin_en":"USA","desc":"咖啡、巧克力与燕麦的浓郁世涛。","desc_en":"A rich stout of coffee, chocolate and oats."},
{"id":91,"name":"老拉斯普京","name_en":"Old Rasputin","brewery":"北岸","brewery_en":"North Coast","cat":"stout","style":"俄式帝国世涛","style_en":"Russian Imperial Stout","abv":"9.0%","origin":"美国","origin_en":"USA","desc":"美式俄式帝国世涛标杆，醇厚焦苦。","desc_en":"A benchmark American RIS—rich and roasty-bitter."},
{"id":92,"name":"Ten FIDY","name_en":"Ten FIDY","brewery":"奥斯卡蓝调","brewery_en":"Oskar Blues","cat":"stout","style":"帝国世涛","style_en":"Imperial Stout","abv":"10.5%","origin":"美国","origin_en":"USA","desc":"罐装帝国世涛，如机油般浓稠。","desc_en":"A canned imperial stout as thick as motor oil."},
{"id":93,"name":"极速世涛","name_en":"Speedway Stout","brewery":"艾尔史密斯","brewery_en":"AleSmith","cat":"stout","style":"帝国世涛","style_en":"Imperial Stout","abv":"12.0%","origin":"美国","origin_en":"USA","desc":"加入咖啡的圣地亚哥帝国世涛名作。","desc_en":"A coffee-laced San Diego imperial stout."},
{"id":94,"name":"雪人帝国世涛","name_en":"Yeti Imperial Stout","brewery":"大分水岭","brewery_en":"Great Divide","cat":"stout","style":"帝国世涛","style_en":"Imperial Stout","abv":"9.5%","origin":"美国","origin_en":"USA","desc":"科罗拉多经典，焦糖与烘焙麦芽厚重。","desc_en":"A Colorado classic, heavy with caramel and roast."},
{"id":95,"name":"左手牛奶世涛","name_en":"Milk Stout Nitro","brewery":"左手","brewery_en":"Left Hand","cat":"stout","style":"牛奶世涛","style_en":"Milk Stout","abv":"6.0%","origin":"美国","origin_en":"USA","desc":"氮气罐装牛奶世涛，绵密顺滑的教科书。","desc_en":"A nitro milk stout—the textbook of creamy smoothness."},
{"id":96,"name":"塞缪尔史密斯燕麦世涛","name_en":"Samuel Smith's Oatmeal Stout","brewery":"塞缪尔史密斯","brewery_en":"Samuel Smith","cat":"stout","style":"燕麦世涛","style_en":"Oatmeal Stout","abv":"5.0%","origin":"英国","origin_en":"UK","desc":"复兴燕麦世涛风格的约克郡经典。","desc_en":"The Yorkshire classic that revived the oatmeal stout."},
{"id":97,"name":"内华达山脉波特","name_en":"Sierra Nevada Porter","brewery":"内华达山脉","brewery_en":"Sierra Nevada","cat":"stout","style":"美式波特","style_en":"American Porter","abv":"5.6%","origin":"美国","origin_en":"USA","desc":"均衡的美式波特，巧克力与咖啡气息。","desc_en":"A balanced American porter of chocolate and coffee."},
{"id":98,"name":"黑丘波特","name_en":"Black Butte Porter","brewery":"迪舒特","brewery_en":"Deschutes","cat":"stout","style":"美式波特","style_en":"American Porter","abv":"5.2%","origin":"美国","origin_en":"USA","desc":"俄勒冈招牌波特，顺滑巧克力奶油感。","desc_en":"Oregon's signature porter—smooth and chocolatey."},
{"id":99,"name":"铁锚波特","name_en":"Anchor Porter","brewery":"铁锚","brewery_en":"Anchor Brewing","cat":"stout","style":"美式波特","style_en":"American Porter","abv":"5.6%","origin":"美国","origin_en":"USA","desc":"1972 年帮助复兴波特风格的旧金山经典。","desc_en":"The 1972 San Francisco classic that helped revive the porter."},
{"id":100,"name":"富勒伦敦波特","name_en":"Fuller's London Porter","brewery":"富勒","brewery_en":"Fuller's","cat":"stout","style":"英式波特","style_en":"English Porter","abv":"5.4%","origin":"英国","origin_en":"UK","desc":"丝滑的伦敦波特，巧克力与太妃糖香。","desc_en":"A silky London porter of chocolate and toffee."},
{"id":101,"name":"双巧克力世涛","name_en":"Double Chocolate Stout","brewery":"扬氏","brewery_en":"Young's","cat":"stout","style":"甜世涛","style_en":"Sweet Stout","abv":"5.2%","origin":"英国","origin_en":"UK","desc":"加入真巧克力的顺滑甜世涛。","desc_en":"A smooth sweet stout made with real chocolate."},

/* ============ 酸啤与野啤 sour ============ */
{"id":102,"name":"康帝龙老古斯","name_en":"Cantillon Gueuze","brewery":"康帝龙","brewery_en":"Cantillon","cat":"sour","style":"老古斯(自然酸酿)","style_en":"Gueuze (Lambic)","abv":"5.0%","origin":"比利时","origin_en":"Belgium","desc":"布鲁塞尔自然发酵的传奇，酸香复杂如香槟。","desc_en":"A Brussels spontaneous-fermentation legend, tart and champagne-like."},
{"id":103,"name":"康帝龙玫瑰","name_en":"Rosé de Gambrinus","brewery":"康帝龙","brewery_en":"Cantillon","cat":"sour","style":"覆盆子兰比克","style_en":"Framboise Lambic","abv":"5.0%","origin":"比利时","origin_en":"Belgium","desc":"覆盆子浸渍的兰比克，酸甜果香。","desc_en":"A raspberry-macerated lambic, tart and fruity."},
{"id":104,"name":"三泉老古斯","name_en":"3 Fonteinen Oude Geuze","brewery":"三泉","brewery_en":"3 Fonteinen","cat":"sour","style":"老古斯","style_en":"Gueuze","abv":"6.0%","origin":"比利时","origin_en":"Belgium","desc":"帕约特兰传统混调老古斯的顶尖代表。","desc_en":"A top exponent of traditional Payottenland blended gueuze."},
{"id":105,"name":"布恩老古斯","name_en":"Boon Oude Geuze","brewery":"布恩","brewery_en":"Boon","cat":"sour","style":"老古斯","style_en":"Gueuze","abv":"7.0%","origin":"比利时","origin_en":"Belgium","desc":"经典混调老古斯，酸度明快易入门。","desc_en":"A classic blended gueuze, bright and approachable."},
{"id":106,"name":"罗登巴赫特级","name_en":"Rodenbach Grand Cru","brewery":"罗登巴赫","brewery_en":"Rodenbach","cat":"sour","style":"佛兰德斯红艾","style_en":"Flanders Red","abv":"6.0%","origin":"比利时","origin_en":"Belgium","desc":"橡木大桶陈酿的佛兰德斯红艾,酸甜似樱桃。","desc_en":"An oak-foudre-aged Flanders red, tart and cherry-like."},
{"id":107,"name":"勃艮第女公爵","name_en":"Duchesse de Bourgogne","brewery":"维哈根","brewery_en":"Verhaeghe","cat":"sour","style":"佛兰德斯红艾","style_en":"Flanders Red","abv":"6.2%","origin":"比利时","origin_en":"Belgium","desc":"甜美圆润的佛兰德斯红艾，酸甜平衡。","desc_en":"A sweetly rounded Flanders red, tart-sweet and balanced."},
{"id":108,"name":"林德曼树莓","name_en":"Lindemans Framboise","brewery":"林德曼","brewery_en":"Lindemans","cat":"sour","style":"果味兰比克","style_en":"Fruit Lambic","abv":"2.5%","origin":"比利时","origin_en":"Belgium","desc":"甜美易饮的覆盆子兰比克，入门酸啤首选。","desc_en":"A sweet, easy raspberry lambic—a gateway sour."},
{"id":109,"name":"祈求","name_en":"Supplication","brewery":"俄罗斯河","brewery_en":"Russian River","cat":"sour","style":"桶陈酸棕艾","style_en":"Barrel-Aged Sour","abv":"7.0%","origin":"美国","origin_en":"USA","desc":"黑皮诺桶陈、酸樱桃浸渍的美式野生艾尔。","desc_en":"A Pinot-barrel-aged sour brown with sour cherries."},
{"id":110,"name":"献祭","name_en":"Consecration","brewery":"俄罗斯河","brewery_en":"Russian River","cat":"sour","style":"桶陈酸艾","style_en":"Barrel-Aged Sour","abv":"10.0%","origin":"美国","origin_en":"USA","desc":"赤霞珠桶陈加黑加仑的复杂酸啤。","desc_en":"A Cabernet-barrel sour with blackcurrants—deep and complex."},
{"id":111,"name":"疯狂","name_en":"La Folie","brewery":"新比利时","brewery_en":"New Belgium","cat":"sour","style":"佛兰德斯酸棕艾","style_en":"Flanders Sour Brown","abv":"7.0%","origin":"美国","origin_en":"USA","desc":"木桶陈酿的美式佛兰德斯酸棕艾先驱。","desc_en":"A pioneering American wood-aged Flanders-style sour brown."},
{"id":112,"name":"西布鲁克古斯","name_en":"Westbrook Gose","brewery":"西布鲁克","brewery_en":"Westbrook","cat":"sour","style":"古斯","style_en":"Gose","abv":"4.0%","origin":"美国","origin_en":"USA","desc":"带海盐与芫荽的清爽古斯，掀起美国古斯热。","desc_en":"A salty-coriander gose that sparked America's gose craze."},
{"id":113,"name":"莱比锡古斯","name_en":"Leipziger Gose","brewery":"巴伐利亚火车站","brewery_en":"Bayerischer Bahnhof","cat":"sour","style":"古斯","style_en":"Gose","abv":"4.6%","origin":"德国","origin_en":"Germany","desc":"复兴莱比锡传统古斯的代表酒厂。","desc_en":"The brewery that revived the traditional Leipzig gose."},
{"id":114,"name":"布恩樱桃","name_en":"Boon Kriek","brewery":"布恩","brewery_en":"Boon","cat":"sour","style":"樱桃兰比克","style_en":"Kriek Lambic","abv":"4.0%","origin":"比利时","origin_en":"Belgium","desc":"整颗樱桃浸渍的传统兰比克。","desc_en":"A traditional lambic macerated on whole cherries."},

/* ============ 琥珀与棕色艾尔 amber ============ */
{"id":115,"name":"胖轮胎","name_en":"Fat Tire Amber Ale","brewery":"新比利时","brewery_en":"New Belgium","cat":"amber","style":"琥珀艾尔","style_en":"Amber Ale","abv":"5.2%","origin":"美国","origin_en":"USA","desc":"科罗拉多的招牌琥珀艾尔，麦香饼干味。","desc_en":"Colorado's signature amber ale—biscuity and malty."},
{"id":116,"name":"铁锚蒸汽","name_en":"Anchor Steam Beer","brewery":"铁锚","brewery_en":"Anchor Brewing","cat":"amber","style":"加州淡爽艾尔(蒸汽)","style_en":"California Common","abv":"4.9%","origin":"美国","origin_en":"USA","desc":"旧金山独有的'蒸汽啤酒',美国精酿的活化石。","desc_en":"San Francisco's unique 'steam beer'—a living fossil of American craft."},
{"id":117,"name":"掘金花蜜","name_en":"Nugget Nectar","brewery":"特罗格","brewery_en":"Tröegs","cat":"amber","style":"帝国琥珀艾尔","style_en":"Imperial Amber","abv":"7.5%","origin":"美国","origin_en":"USA","desc":"季节限定帝国琥珀,酒花香如爆炸般浓郁。","desc_en":"A seasonal imperial amber, explosively hoppy."},
{"id":118,"name":"纽卡斯尔棕艾","name_en":"Newcastle Brown Ale","brewery":"纽卡斯尔","brewery_en":"Newcastle","cat":"amber","style":"英式棕艾","style_en":"English Brown Ale","abv":"4.7%","origin":"英国","origin_en":"UK","desc":"英格兰东北的经典棕艾,昵称'狗'。","desc_en":"The classic Northeast English brown ale, nicknamed 'the Dog'."},
{"id":119,"name":"坚果棕艾","name_en":"Samuel Smith's Nut Brown Ale","brewery":"塞缪尔史密斯","brewery_en":"Samuel Smith","cat":"amber","style":"英式棕艾","style_en":"English Brown Ale","abv":"5.0%","origin":"英国","origin_en":"UK","desc":"约克郡坚果棕艾,烤坚果与焦糖气息。","desc_en":"A Yorkshire brown ale of toasted nuts and caramel."},
{"id":120,"name":"碎颅者","name_en":"Skull Splitter","brewery":"奥克尼","brewery_en":"Orkney","cat":"amber","style":"苏格兰烈艾","style_en":"Wee Heavy","abv":"8.5%","origin":"英国","origin_en":"UK","desc":"以维京首领命名的浓烈苏格兰艾尔。","desc_en":"A potent Scotch ale named after a Viking earl."},
{"id":121,"name":"肮脏混蛋","name_en":"Dirty Bastard","brewery":"创始人","brewery_en":"Founders","cat":"amber","style":"苏格兰艾尔","style_en":"Scotch Ale","abv":"8.5%","origin":"美国","origin_en":"USA","desc":"七种麦芽酿造的浓郁苏格兰风艾尔。","desc_en":"A rich Scotch-style ale brewed with seven malts."},
{"id":122,"name":"阿拉斯加琥珀","name_en":"Alaskan Amber","brewery":"阿拉斯加","brewery_en":"Alaskan","cat":"amber","style":"老式琥珀(Altbier)","style_en":"Amber Altbier","abv":"5.3%","origin":"美国","origin_en":"USA","desc":"依淘金时代配方酿造的德式老啤风琥珀。","desc_en":"An Altbier-style amber based on a gold-rush-era recipe."},
{"id":123,"name":"三山","name_en":"3 Monts","brewery":"圣西尔维斯特","brewery_en":"Saint-Sylvestre","cat":"amber","style":"存储艾尔(Bière de Garde)","style_en":"Bière de Garde","abv":"8.5%","origin":"法国","origin_en":"France","desc":"法国北部农舍风格的金色存储艾尔。","desc_en":"A golden farmhouse-style Bière de Garde from northern France."},

/* ============ 烈性与桶陈 strong ============ */
{"id":124,"name":"波本郡世涛","name_en":"Bourbon County Brand Stout","brewery":"鹅岛","brewery_en":"Goose Island","cat":"strong","style":"波本桶陈帝国世涛","style_en":"BA Imperial Stout","abv":"14.7%","origin":"美国","origin_en":"USA","desc":"开创波本桶陈世涛品类的传奇,每年黑五发售。","desc_en":"The legend that created the bourbon-barrel stout category, out each Black Friday."},
{"id":125,"name":"肯塔基早餐世涛 KBS","name_en":"Kentucky Breakfast Stout","brewery":"创始人","brewery_en":"Founders","cat":"strong","style":"波本桶陈帝国世涛","style_en":"BA Imperial Stout","abv":"12.0%","origin":"美国","origin_en":"USA","desc":"咖啡巧克力早餐世涛的波本桶陈版本。","desc_en":"The bourbon-barrel version of the coffee-chocolate breakfast stout."},
{"id":126,"name":"抛物线","name_en":"Parabola","brewery":"石墙","brewery_en":"Firestone Walker","cat":"strong","style":"波本桶陈帝国世涛","style_en":"BA Imperial Stout","abv":"13.0%","origin":"美国","origin_en":"USA","desc":"波本桶陈帝国世涛顶流,浓稠似糖浆。","desc_en":"A top-tier bourbon-barrel imperial stout, syrup-thick."},
{"id":127,"name":"黑暗领主","name_en":"Dark Lord","brewery":"三个弗洛伊德","brewery_en":"Three Floyds","cat":"strong","style":"俄式帝国世涛","style_en":"Russian Imperial Stout","abv":"15.0%","origin":"美国","origin_en":"USA","desc":"每年'黑暗领主日'限量发售的膜拜级世涛。","desc_en":"A cult stout released only on annual 'Dark Lord Day'."},
{"id":128,"name":"乌托邦","name_en":"Utopias","brewery":"波士顿啤酒公司","brewery_en":"Samuel Adams","cat":"strong","style":"桶陈极烈艾尔","style_en":"Barrel-Aged Extreme","abv":"28%","origin":"美国","origin_en":"USA","desc":"无碳酸、如波特酒般的极烈艾尔,数年桶陈。","desc_en":"An uncarbonated, port-like extreme ale aged for years in barrels."},
{"id":129,"name":"世界之涛","name_en":"World Wide Stout","brewery":"角鲨头","brewery_en":"Dogfish Head","cat":"strong","style":"帝国世涛","style_en":"Imperial Stout","abv":"18%","origin":"美国","origin_en":"USA","desc":"曾是世界最烈的啤酒之一,近乎烈酒。","desc_en":"Once among the world's strongest beers, nearly a spirit."},
{"id":130,"name":"120分钟IPA","name_en":"120 Minute IPA","brewery":"角鲨头","brewery_en":"Dogfish Head","cat":"strong","style":"极烈帝国IPA","style_en":"Imperial IPA","abv":"18%","origin":"美国","origin_en":"USA","desc":"连续投花两小时、再干投的极烈IPA。","desc_en":"Hopped continuously for two hours then dry-hopped—an extreme IPA."},
{"id":131,"name":"大脚怪大麦酒","name_en":"Bigfoot Barleywine","brewery":"内华达山脉","brewery_en":"Sierra Nevada","cat":"strong","style":"美式大麦酒","style_en":"American Barleywine","abv":"9.6%","origin":"美国","origin_en":"USA","desc":"每年冬季发售、适合窖藏的美式大麦酒经典。","desc_en":"A cellar-worthy American barleywine released each winter."},
{"id":132,"name":"老雾号大麦酒","name_en":"Old Foghorn","brewery":"铁锚","brewery_en":"Anchor Brewing","cat":"strong","style":"美式大麦酒","style_en":"American Barleywine","abv":"8.8%","origin":"美国","origin_en":"USA","desc":"美国最早的大麦酒之一(1975)。","desc_en":"One of the first American barleywines (1975)."},
{"id":133,"name":"托马斯哈代艾尔","name_en":"Thomas Hardy's Ale","brewery":"托马斯哈代","brewery_en":"Thomas Hardy's","cat":"strong","style":"英式大麦酒","style_en":"English Barleywine","abv":"11.7%","origin":"英国","origin_en":"UK","desc":"可陈放数十年的传奇英式大麦酒。","desc_en":"A legendary English barleywine that ages for decades."},
{"id":134,"name":"库里厄三料","name_en":"Curieux","brewery":"阿拉加什","brewery_en":"Allagash","cat":"strong","style":"波本桶陈三料","style_en":"BA Tripel","abv":"11.0%","origin":"美国","origin_en":"USA","desc":"波本桶陈的比利时风三料,香草椰香。","desc_en":"A bourbon-barrel-aged Belgian-style tripel with vanilla and coconut."},
{"id":135,"name":"阿文丁冰博克","name_en":"Aventinus Eisbock","brewery":"施耐德","brewery_en":"Schneider","cat":"strong","style":"冰博克","style_en":"Eisbock","abv":"12.0%","origin":"德国","origin_en":"Germany","desc":"冷冻浓缩的小麦博克,李子与太妃糖浓郁。","desc_en":"A freeze-concentrated wheat bock, rich with plum and toffee."},
{"id":136,"name":"老库存艾尔","name_en":"Old Stock Ale","brewery":"北岸","brewery_en":"North Coast","cat":"strong","style":"英式老艾尔","style_en":"Old Ale","abv":"11.9%","origin":"美国","origin_en":"USA","desc":"适合窖藏、随年份变化的英式老艾尔。","desc_en":"A cellarable old ale that evolves with vintage."},

/* ============ 特色与季节 specialty ============ */
{"id":137,"name":"施兰卡烟熏","name_en":"Aecht Schlenkerla Rauchbier Märzen","brewery":"施兰卡","brewery_en":"Schlenkerla","cat":"specialty","style":"烟熏拉格","style_en":"Rauchbier (Smoked)","abv":"5.1%","origin":"德国","origin_en":"Germany","desc":"班贝格榉木烟熏麦芽酿造,培根般烟熏味。","desc_en":"Brewed with Bamberg beechwood-smoked malt—bacon-like and smoky."},
{"id":138,"name":"南瓜王","name_en":"Pumpking","brewery":"南方一线","brewery_en":"Southern Tier","cat":"specialty","style":"南瓜艾尔","style_en":"Pumpkin Ale","abv":"8.6%","origin":"美国","origin_en":"USA","desc":"如南瓜派般的秋季帝国南瓜艾尔。","desc_en":"An autumn imperial pumpkin ale like pumpkin pie."},
{"id":139,"name":"覆盆子","name_en":"Rübæus","brewery":"创始人","brewery_en":"Founders","cat":"specialty","style":"覆盆子果啤","style_en":"Raspberry Ale","abv":"5.7%","origin":"美国","origin_en":"USA","desc":"纯覆盆子酿造的粉红果味艾尔。","desc_en":"A pink fruit ale made purely with raspberries."},
{"id":140,"name":"茵尼斯橡木","name_en":"Innis & Gunn Original","brewery":"茵尼斯与冈恩","brewery_en":"Innis & Gunn","cat":"specialty","style":"橡木桶陈艾尔","style_en":"Oak-Aged Ale","abv":"6.6%","origin":"英国","origin_en":"UK","desc":"苏格兰橡木桶陈艾尔,香草太妃糖气息。","desc_en":"A Scottish oak-aged ale of vanilla and toffee."},
{"id":141,"name":"西瓜小麦","name_en":"Hell or High Watermelon","brewery":"第21修正案","brewery_en":"21st Amendment","cat":"specialty","style":"西瓜小麦","style_en":"Fruit Wheat","abv":"4.9%","origin":"美国","origin_en":"USA","desc":"真西瓜酿造的夏日小麦啤酒。","desc_en":"A summer wheat beer brewed with real watermelon."},
{"id":142,"name":"迈达斯之触","name_en":"Midas Touch","brewery":"角鲨头","brewery_en":"Dogfish Head","cat":"specialty","style":"古法艾尔","style_en":"Ancient Ale","abv":"9.0%","origin":"美国","origin_en":"USA","desc":"依 2700 年前墓穴残留复原的蜂蜜藏红花古酒。","desc_en":"Recreated from 2,700-year-old tomb residue—honey, grape and saffron."},
{"id":143,"name":"威斯康星比利时红","name_en":"Wisconsin Belgian Red","brewery":"新格拉鲁斯","brewery_en":"New Glarus","cat":"specialty","style":"樱桃果啤","style_en":"Cherry Fruit Ale","abv":"4.0%","origin":"美国","origin_en":"USA","desc":"每升用一磅樱桃酿造,只在威斯康星发售的传奇果啤。","desc_en":"Brewed with a pound of cherries per liter—a legend sold only in Wisconsin."},
{"id":144,"name":"香蕉面包啤酒","name_en":"Banana Bread Beer","brewery":"威尔斯","brewery_en":"Wells","cat":"specialty","style":"果味艾尔","style_en":"Fruit Ale","abv":"5.2%","origin":"英国","origin_en":"UK","desc":"加入真香蕉的英式风味艾尔。","desc_en":"An English-style ale brewed with real bananas."},

/* ======== 第 2 批扩充：约 56 款，向 1001 推进（145–200） ======== */

/* ---- 拉格/皮尔森 ---- */
{"id":145,"name":"斯巴顿十月节","name_en":"Spaten Oktoberfestbier","brewery":"斯巴顿","brewery_en":"Spaten","cat":"lager","style":"三月/十月节拉格","style_en":"Märzen","abv":"5.9%","origin":"德国","origin_en":"Germany","desc":"慕尼黑六大之一的经典十月节拉格。","desc_en":"A classic Oktoberfest lager from one of Munich's big six."},
{"id":146,"name":"维腾堡巴洛克黑","name_en":"Weltenburger Kloster Barock Dunkel","brewery":"维腾堡修道院","brewery_en":"Weltenburger","cat":"lager","style":"慕尼黑黑拉格","style_en":"Munich Dunkel","abv":"4.7%","origin":"德国","origin_en":"Germany","desc":"多瑙河畔古修道院酒厂的焦香黑拉格。","desc_en":"A malty dark lager from an ancient Danube abbey brewery."},
{"id":147,"name":"沃斯乐皮尔森","name_en":"Warsteiner Premium","brewery":"沃斯乐","brewery_en":"Warsteiner","cat":"lager","style":"德式皮尔森","style_en":"German Pils","abv":"4.8%","origin":"德国","origin_en":"Germany","desc":"德国家族酒厂出品的清爽皮尔森。","desc_en":"A crisp Pils from one of Germany's largest family breweries."},
{"id":148,"name":"罗格死鬼","name_en":"Rogue Dead Guy Ale","brewery":"罗格","brewery_en":"Rogue","cat":"lager","style":"梅博克","style_en":"Maibock","abv":"6.8%","origin":"美国","origin_en":"USA","desc":"以骷髅标志闻名的美式梅博克。","desc_en":"An American Maibock famous for its skeleton mascot."},
{"id":149,"name":"五大湖艾略特·内斯","name_en":"Eliot Ness","brewery":"五大湖","brewery_en":"Great Lakes","cat":"lager","style":"琥珀拉格","style_en":"Amber Lager","abv":"6.2%","origin":"美国","origin_en":"USA","desc":"以禁酒英雄命名的维也纳式琥珀拉格。","desc_en":"A Vienna-style amber lager named for the Prohibition agent."},
{"id":150,"name":"魔鬼脊维也纳拉格","name_en":"Devils Backbone Vienna Lager","brewery":"魔鬼脊","brewery_en":"Devils Backbone","cat":"lager","style":"维也纳拉格","style_en":"Vienna Lager","abv":"4.9%","origin":"美国","origin_en":"USA","desc":"屡获大奖的弗吉尼亚维也纳拉格。","desc_en":"A much-decorated Virginia Vienna lager."},
{"id":151,"name":"普夫瑞姆皮尔森","name_en":"pFriem Pilsner","brewery":"普夫瑞姆","brewery_en":"pFriem","cat":"lager","style":"德式皮尔森","style_en":"German Pils","abv":"4.9%","origin":"美国","origin_en":"USA","desc":"俄勒冈精酿皮尔森，脆爽花香。","desc_en":"An Oregon craft Pils, crisp and floral."},
{"id":152,"name":"城市栗子 Stammtisch","name_en":"Urban Chestnut Stammtisch","brewery":"城市栗子","brewery_en":"Urban Chestnut","cat":"lager","style":"德式皮尔森","style_en":"German Pils","abv":"5.4%","origin":"美国","origin_en":"USA","desc":"圣路易斯德式传统皮尔森。","desc_en":"A St. Louis German-tradition Pils."},
{"id":153,"name":"艾恩贝克淡博克","name_en":"Einbecker Ur-Bock Hell","brewery":"艾恩贝克","brewery_en":"Einbecker","cat":"lager","style":"淡色博克","style_en":"Heller Bock","abv":"6.5%","origin":"德国","origin_en":"Germany","desc":"博克啤酒发源地艾恩贝克的淡色博克。","desc_en":"A pale bock from Einbeck, birthplace of the style."},
{"id":154,"name":"山姆亚当斯十月节","name_en":"Samuel Adams Octoberfest","brewery":"波士顿啤酒公司","brewery_en":"Boston Beer Co.","cat":"lager","style":"三月/十月节拉格","style_en":"Märzen","abv":"5.3%","origin":"美国","origin_en":"USA","desc":"美国最畅销的秋季十月节啤酒之一。","desc_en":"One of America's best-selling autumn Oktoberfest beers."},

/* ---- 淡色艾尔 ---- */
{"id":155,"name":"戴尔淡色艾尔","name_en":"Dale's Pale Ale","brewery":"奥斯卡蓝调","brewery_en":"Oskar Blues","cat":"pale","style":"美式淡色艾尔","style_en":"American Pale Ale","abv":"6.5%","origin":"美国","origin_en":"USA","desc":"精酿罐装革命的先驱之作。","desc_en":"A pioneer of the craft-beer-in-a-can revolution."},
{"id":156,"name":"阿尔法之王","name_en":"Alpha King","brewery":"三个弗洛伊德","brewery_en":"Three Floyds","cat":"pale","style":"美式淡色艾尔","style_en":"American Pale Ale","abv":"6.6%","origin":"美国","origin_en":"USA","desc":"印第安纳膜拜酒厂的招牌淡色艾尔。","desc_en":"The flagship pale ale from a cult Indiana brewery."},
{"id":157,"name":"峰会超级淡色","name_en":"Summit Extra Pale Ale","brewery":"峰会","brewery_en":"Summit","cat":"pale","style":"美式淡色艾尔","style_en":"American Pale Ale","abv":"5.3%","origin":"美国","origin_en":"USA","desc":"明尼苏达常青款淡色艾尔。","desc_en":"A Minnesota mainstay pale ale."},
{"id":158,"name":"山丘农庄爱德华","name_en":"Edward","brewery":"山丘农庄","brewery_en":"Hill Farmstead","cat":"pale","style":"美式淡色艾尔","style_en":"American Pale Ale","abv":"5.2%","origin":"美国","origin_en":"USA","desc":"佛蒙特传奇酒厂以祖父命名的膜拜淡色艾尔。","desc_en":"A cult pale ale named after the founder's grandfather."},
{"id":159,"name":"石墙双桶艾尔","name_en":"Double Barrel Ale","brewery":"石墙","brewery_en":"Firestone Walker","cat":"pale","style":"英式淡色艾尔","style_en":"English Pale Ale","abv":"5.0%","origin":"美国","origin_en":"USA","desc":"部分橡木桶发酵的英式风淡色艾尔。","desc_en":"An English-style pale ale partly fermented in oak."},
{"id":160,"name":"压舱石格鲁尼恩","name_en":"Grunion Pale Ale","brewery":"压舱石","brewery_en":"Ballast Point","cat":"pale","style":"美式淡色艾尔","style_en":"American Pale Ale","abv":"5.5%","origin":"美国","origin_en":"USA","desc":"圣地亚哥柑橘调淡色艾尔。","desc_en":"A citrusy San Diego pale ale."},

/* ---- IPA ---- */
{"id":161,"name":"内华达山脉鱼雷","name_en":"Torpedo Extra IPA","brewery":"内华达山脉","brewery_en":"Sierra Nevada","cat":"ipa","style":"美式IPA","style_en":"American IPA","abv":"7.2%","origin":"美国","origin_en":"USA","desc":"独创'鱼雷'干投装置酿造的常青 IPA。","desc_en":"Brewed with its signature 'Torpedo' dry-hopping device."},
{"id":162,"name":"拉古尼塔斯 Sucks","name_en":"Lagunitas Sucks","brewery":"拉古尼塔斯","brewery_en":"Lagunitas","cat":"ipa","style":"双料IPA","style_en":"Double IPA","abv":"7.85%","origin":"美国","origin_en":"USA","desc":"因缺货玩笑而生、意外走红的双料IPA。","desc_en":"A double IPA born from an out-of-stock joke that stuck."},
{"id":163,"name":"创始人世纪IPA","name_en":"Centennial IPA","brewery":"创始人","brewery_en":"Founders","cat":"ipa","style":"美式IPA","style_en":"American IPA","abv":"7.2%","origin":"美国","origin_en":"USA","desc":"单一世纪花的均衡美式IPA。","desc_en":"A balanced all-Centennial American IPA."},
{"id":164,"name":"摩登时代烈焰世界","name_en":"Blazing World","brewery":"摩登时代","brewery_en":"Modern Times","cat":"ipa","style":"琥珀IPA","style_en":"Amber IPA","abv":"6.8%","origin":"美国","origin_en":"USA","desc":"麦香与酒花并重的琥珀色 IPA。","desc_en":"An amber IPA balancing malt and hops."},
{"id":165,"name":"推倒歌利亚苏王","name_en":"King Sue","brewery":"推倒歌利亚","brewery_en":"Toppling Goliath","cat":"ipa","style":"双料IPA","style_en":"Double IPA","abv":"7.8%","origin":"美国","origin_en":"USA","desc":"'假苏'的加强版，西楚花双料IPA。","desc_en":"The imperial version of Pseudo Sue, all Citra."},
{"id":166,"name":"树屋绿","name_en":"Green","brewery":"树屋","brewery_en":"Tree House","cat":"ipa","style":"新英格兰IPA","style_en":"New England IPA","abv":"7.5%","origin":"美国","origin_en":"USA","desc":"树屋最抢手的浑浊 IPA 之一。","desc_en":"One of Tree House's most sought-after hazy IPAs."},
{"id":167,"name":"特里利厄姆堡点","name_en":"Fort Point Pale Ale","brewery":"特里利厄姆","brewery_en":"Trillium","cat":"ipa","style":"新英格兰淡色艾尔","style_en":"New England Pale Ale","abv":"6.6%","origin":"美国","origin_en":"USA","desc":"波士顿膜拜酒厂的招牌浑浊淡色艾尔。","desc_en":"The signature hazy pale from a cult Boston brewery."},
{"id":168,"name":"另一半全绿","name_en":"All Green Everything","brewery":"另一半","brewery_en":"Other Half","cat":"ipa","style":"三料IPA","style_en":"Triple IPA","abv":"10.5%","origin":"美国","origin_en":"USA","desc":"纽约浑浊浪潮代表的三料IPA。","desc_en":"A triple IPA emblematic of NYC's haze wave."},
{"id":169,"name":"多汁碎块","name_en":"Juicy Bits","brewery":"焊接工坊","brewery_en":"WeldWerks","cat":"ipa","style":"新英格兰IPA","style_en":"New England IPA","abv":"6.7%","origin":"美国","origin_en":"USA","desc":"科罗拉多多汁浑浊 IPA 代表作。","desc_en":"A juicy Colorado hazy IPA flagship."},
{"id":170,"name":"巫毒游侠帝国IPA","name_en":"Voodoo Ranger Imperial IPA","brewery":"新比利时","brewery_en":"New Belgium","cat":"ipa","style":"帝国IPA","style_en":"Imperial IPA","abv":"9.0%","origin":"美国","origin_en":"USA","desc":"美国销量领先的帝国 IPA 系列。","desc_en":"One of America's best-selling imperial IPA lines."},

/* ---- 小麦 ---- */
{"id":171,"name":"维森维图斯","name_en":"Weihenstephaner Vitus","brewery":"维森斯特凡","brewery_en":"Weihenstephan","cat":"wheat","style":"小麦博克","style_en":"Weizenbock","abv":"7.7%","origin":"德国","origin_en":"Germany","desc":"金色小麦博克，屡获世界大奖。","desc_en":"A pale wheat bock laden with world awards."},
{"id":172,"name":"内华达山脉窖藏小麦","name_en":"Kellerweis","brewery":"内华达山脉","brewery_en":"Sierra Nevada","cat":"wheat","style":"德式酵母小麦","style_en":"Hefeweizen","abv":"4.8%","origin":"美国","origin_en":"USA","desc":"开放式发酵酿造的美式德式小麦。","desc_en":"An open-fermented American take on Hefeweizen."},
{"id":173,"name":"艾英格小麦","name_en":"Ayinger Bräuweisse","brewery":"艾英格","brewery_en":"Ayinger","cat":"wheat","style":"德式酵母小麦","style_en":"Hefeweizen","abv":"5.1%","origin":"德国","origin_en":"Germany","desc":"巴伐利亚经典酵母小麦。","desc_en":"A classic Bavarian Hefeweizen."},
{"id":174,"name":"麦泽尔小麦","name_en":"Maisel's Weisse Original","brewery":"麦泽尔","brewery_en":"Maisel","cat":"wheat","style":"德式酵母小麦","style_en":"Hefeweizen","abv":"5.2%","origin":"德国","origin_en":"Germany","desc":"拜罗伊特家族酒厂的招牌小麦。","desc_en":"The flagship wheat from a Bayreuth family brewery."},

/* ---- 比利时艾尔 ---- */
{"id":175,"name":"金卡露经典","name_en":"Gouden Carolus Classic","brewery":"锚酒厂","brewery_en":"Het Anker","cat":"belgian","style":"比利时深色烈艾","style_en":"Belgian Dark Strong","abv":"8.5%","origin":"比利时","origin_en":"Belgium","desc":"梅赫伦古酒厂的焦糖深色烈艾。","desc_en":"A caramel-rich dark strong ale from a Mechelen classic."},
{"id":176,"name":"大道 7 号罐","name_en":"Tank 7","brewery":"大道","brewery_en":"Boulevard","cat":"belgian","style":"季节啤酒","style_en":"Saison","abv":"8.5%","origin":"美国","origin_en":"USA","desc":"堪萨斯城招牌农舍季节艾尔。","desc_en":"Kansas City's signature farmhouse saison."},
{"id":177,"name":"马杜斯 10 号","name_en":"Maredsous 10","brewery":"督威摩盖特","brewery_en":"Duvel Moortgat","cat":"belgian","style":"三料","style_en":"Tripel","abv":"10.0%","origin":"比利时","origin_en":"Belgium","desc":"修道院授权的浓烈金色三料。","desc_en":"A strong golden abbey tripel."},
{"id":178,"name":"诅咒","name_en":"Maudite","brewery":"尤妮布罗","brewery_en":"Unibroue","cat":"belgian","style":"比利时深色烈艾","style_en":"Belgian Dark Strong","abv":"8.0%","origin":"加拿大","origin_en":"Canada","desc":"魁北克红铜色比利时风烈艾。","desc_en":"A copper-red Belgian-style strong ale from Quebec."},
{"id":179,"name":"圣佛洋三料","name_en":"St. Feuillien Tripel","brewery":"圣佛洋","brewery_en":"St. Feuillien","cat":"belgian","style":"三料","style_en":"Tripel","abv":"8.5%","origin":"比利时","origin_en":"Belgium","desc":"瓦隆修道院风格金色三料。","desc_en":"A golden Walloon abbey-style tripel."},
{"id":180,"name":"亨德里克三料","name_en":"Straffe Hendrik Tripel","brewery":"半月","brewery_en":"De Halve Maan","cat":"belgian","style":"三料","style_en":"Tripel","abv":"9.0%","origin":"比利时","origin_en":"Belgium","desc":"布鲁日老酒厂'强壮的亨德里克'三料。","desc_en":"'Strong Henry' tripel from a historic Bruges brewery."},

/* ---- 世涛与波特 ---- */
{"id":181,"name":"埃德蒙·菲茨杰拉德波特","name_en":"Edmund Fitzgerald Porter","brewery":"五大湖","brewery_en":"Great Lakes","cat":"stout","style":"波特","style_en":"American Porter","abv":"5.8%","origin":"美国","origin_en":"USA","desc":"以沉船命名的经典浓郁波特。","desc_en":"A robust porter named for a famous shipwreck."},
{"id":182,"name":"迪舒特黑曜石世涛","name_en":"Obsidian Stout","brewery":"迪舒特","brewery_en":"Deschutes","cat":"stout","style":"美式世涛","style_en":"American Stout","abv":"6.4%","origin":"美国","origin_en":"USA","desc":"俄勒冈顺滑烘焙美式世涛。","desc_en":"A smooth, roasty Oregon American stout."},
{"id":183,"name":"健力士海外特浓世涛","name_en":"Guinness Foreign Extra Stout","brewery":"健力士","brewery_en":"Guinness","cat":"stout","style":"海外特浓世涛","style_en":"Foreign Extra Stout","abv":"7.5%","origin":"爱尔兰","origin_en":"Ireland","desc":"更烈更浓的健力士出口型世涛，源自 19 世纪。","desc_en":"A stronger, bolder Guinness export stout dating to the 1800s."},
{"id":184,"name":"胜利风暴之王","name_en":"Storm King","brewery":"胜利酿造","brewery_en":"Victory","cat":"stout","style":"帝国世涛","style_en":"Imperial Stout","abv":"9.1%","origin":"美国","origin_en":"USA","desc":"大量投花的宾州帝国世涛。","desc_en":"A heavily hopped Pennsylvania imperial stout."},
{"id":185,"name":"贝尔卡拉马祖世涛","name_en":"Kalamazoo Stout","brewery":"贝尔","brewery_en":"Bell's","cat":"stout","style":"美式世涛","style_en":"American Stout","abv":"6.0%","origin":"美国","origin_en":"USA","desc":"密歇根招牌美式世涛，带甘草气息。","desc_en":"A Michigan flagship stout with a hint of licorice."},
{"id":186,"name":"创始人波特","name_en":"Founders Porter","brewery":"创始人","brewery_en":"Founders","cat":"stout","style":"波特","style_en":"American Porter","abv":"6.5%","origin":"美国","origin_en":"USA","desc":"厚重丝滑、巧克力浓郁的美式波特。","desc_en":"A full-bodied, silky, chocolate-rich American porter."},

/* ---- 酸啤与野啤 ---- */
{"id":187,"name":"蒂尔坎老古斯","name_en":"Tilquin Oude Gueuze","brewery":"蒂尔坎","brewery_en":"Tilquin","cat":"sour","style":"老古斯","style_en":"Gueuze","abv":"7.0%","origin":"比利时","origin_en":"Belgium","desc":"瓦隆唯一的兰比克混调厂出品。","desc_en":"From the only lambic blendery in Wallonia."},
{"id":188,"name":"情人金带","name_en":"Liefmans Goudenband","brewery":"情人","brewery_en":"Liefmans","cat":"sour","style":"佛兰德斯棕艾","style_en":"Flanders Oud Bruin","abv":"8.0%","origin":"比利时","origin_en":"Belgium","desc":"混合陈酿的东佛兰德斯酸棕艾。","desc_en":"A blended, aged East Flanders sour brown."},
{"id":189,"name":"快乐南瓜红","name_en":"La Roja","brewery":"快乐南瓜","brewery_en":"Jolly Pumpkin","cat":"sour","style":"美式野生琥珀酸艾","style_en":"Wild Amber Sour","abv":"7.2%","origin":"美国","origin_en":"USA","desc":"密歇根全桶陈野生发酵琥珀酸艾。","desc_en":"A barrel-aged, wild-fermented amber sour from Michigan."},
{"id":190,"name":"皇帝陈酿淡色酸","name_en":"Petrus Aged Pale","brewery":"布拉班德","brewery_en":"De Brabandere","cat":"sour","style":"橡木陈酿酸金艾","style_en":"Oak-Aged Sour Blonde","abv":"7.3%","origin":"比利时","origin_en":"Belgium","desc":"橡木大桶陈三年的纯酸金啤，常用于调配。","desc_en":"A pure sour blonde aged three years in oak foudres."},

/* ---- 琥珀与棕色艾尔 ---- */
{"id":191,"name":"奥德尔 90 先令","name_en":"90 Shilling Ale","brewery":"奥德尔","brewery_en":"Odell","cat":"amber","style":"苏格兰式艾尔","style_en":"Scottish Ale","abv":"5.3%","origin":"美国","origin_en":"USA","desc":"科罗拉多顺滑麦香的苏格兰式艾尔。","desc_en":"A smooth, malty Colorado Scottish-style ale."},
{"id":192,"name":"布鲁克林棕艾","name_en":"Brooklyn Brown Ale","brewery":"布鲁克林","brewery_en":"Brooklyn","cat":"amber","style":"美式棕艾","style_en":"American Brown Ale","abv":"5.6%","origin":"美国","origin_en":"USA","desc":"纽约烘焙麦芽风味的美式棕艾。","desc_en":"A malty, roasty New York American brown ale."},
{"id":193,"name":"贝尔琥珀艾尔","name_en":"Bell's Amber Ale","brewery":"贝尔","brewery_en":"Bell's","cat":"amber","style":"琥珀艾尔","style_en":"Amber Ale","abv":"5.8%","origin":"美国","origin_en":"USA","desc":"密歇根元老级均衡琥珀艾尔。","desc_en":"A balanced amber ale, a Michigan mainstay."},

/* ---- 烈性与桶陈 ---- */
{"id":194,"name":"创始人林地混蛋","name_en":"Backwoods Bastard","brewery":"创始人","brewery_en":"Founders","cat":"strong","style":"波本桶陈苏格兰艾尔","style_en":"BA Scotch Ale","abv":"11.4%","origin":"美国","origin_en":"USA","desc":"'肮脏混蛋'的波本桶陈版，香草太妃糖气息。","desc_en":"The bourbon-barrel version of Dirty Bastard, rich with vanilla and toffee."},
{"id":195,"name":"黑色星期二","name_en":"Black Tuesday","brewery":"布鲁瑞","brewery_en":"The Bruery","cat":"strong","style":"波本桶陈帝国世涛","style_en":"BA Imperial Stout","abv":"19.5%","origin":"美国","origin_en":"USA","desc":"波本桶陈的极烈帝国世涛，年度膜拜发售。","desc_en":"An extreme bourbon-barrel imperial stout, a cult annual release."},
{"id":196,"name":"狗毛亚当","name_en":"Adam","brewery":"狗毛","brewery_en":"Hair of the Dog","cat":"strong","style":"老艾尔","style_en":"Old Ale","abv":"10.0%","origin":"美国","origin_en":"USA","desc":"波特兰复原古法的烟熏浓烈老艾尔。","desc_en":"A smoky, strong old ale reviving a historic style in Portland."},

/* ---- 特色与季节 ---- */
{"id":197,"name":"新格拉鲁斯覆盆子挞","name_en":"Raspberry Tart","brewery":"新格拉鲁斯","brewery_en":"New Glarus","cat":"specialty","style":"覆盆子果啤","style_en":"Raspberry Fruit Ale","abv":"4.0%","origin":"美国","origin_en":"USA","desc":"只在威斯康星发售的覆盆子果啤名作。","desc_en":"A celebrated raspberry fruit ale sold only in Wisconsin."},
{"id":198,"name":"南方一线焦糖布丁","name_en":"Crème Brûlée","brewery":"南方一线","brewery_en":"Southern Tier","cat":"specialty","style":"帝国牛奶世涛","style_en":"Imperial Milk Stout","abv":"9.6%","origin":"美国","origin_en":"USA","desc":"香草焦糖如甜点般的帝国牛奶世涛。","desc_en":"A dessert-like imperial milk stout of vanilla and caramel."},
{"id":199,"name":"罗格巧克力世涛","name_en":"Rogue Chocolate Stout","brewery":"罗格","brewery_en":"Rogue","cat":"specialty","style":"巧克力世涛","style_en":"Chocolate Stout","abv":"5.8%","origin":"美国","origin_en":"USA","desc":"加入真可可的顺滑巧克力世涛。","desc_en":"A smooth chocolate stout brewed with real cocoa."},
{"id":200,"name":"施兰卡烟熏博克","name_en":"Aecht Schlenkerla Urbock","brewery":"施兰卡","brewery_en":"Schlenkerla","cat":"specialty","style":"烟熏博克","style_en":"Smoked Bock","abv":"6.5%","origin":"德国","origin_en":"Germany","desc":"班贝格榉木烟熏的季节限定烈性博克。","desc_en":"A seasonal strong bock with Bamberg beechwood smoke."}

];
